version: "3"

services:
  front:
    container_name: front
    build:
      context: ./front/
      dockerfile: Dockerfile
    networks:
      - my-network
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - NEXT_PUBLIC_MAP_KEY=AIzaSyAXQKN35kt5AtQZnlb8zR97tW6sR3K2ejE
      - NEXT_PUBLIC_BASE_URL=http://localhost:3000
    command: ["npm", "run", "dev"]

  postgres-database:
    container_name: postgres-db
    image: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    restart: always
    networks:
      - my-network
    volumes:
      - postgres-data:/data/db
    environment:
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=fitness-db
  backend:
    container_name: backend
    build:
      context: ./back/
      dockerfile: Dockerfile
    networks:
      - my-network
    volumes:
      - ./back/src:/usr/app/src
      - ./back/nodemon.json:/usr/app/nodemon.json
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://admin:admin123@postgres-db:5432/fitness-db?schema=public
      - JWT_TOKEN=somesecretkey
      - GMAIL_MAIL=tomic4385@gmail.com
      - GMAIL_PASS=ikdp ydqp cfbd qgaf
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - postgres-database
    command: ["npm", "run", "dev"]

volumes:
  postgres-data:
    driver: local
networks:
  my-network:
